// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbiitcdnsssvdwjdxhbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiaWl0Y2Ruc3NzdmR3amR4aGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NjQ1NDMsImV4cCI6MjA1MjE0MDU0M30.AemdPs0uYoZtSeO6U5smAO-FW0u4DP7oeeBdJpYnZbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);